# Generated by Django 4.1.3 on 2023-03-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('what_to_do', models.TextField(blank=True, null=True)),
                ('when_to_do', models.DateField(blank=True, null=True)),
                ('do_status', models.BooleanField(default=True)),
                ('working_status', models.BooleanField(default=False)),
                ('done_status', models.BooleanField(default=False)),
            ],
        ),
    ]
